### ISSUE TITLE
How do I inject errors into the GPU hardware?

### ISSUE THREAD

**Issue by eafayao** [NVIDIA/DCGM#124]
https://github.com/NVIDIA/DCGM/blob/cc3fe64d966d956cebba3e3ff1334786dd767d35/dcgmlib/src/DcgmCacheManager.cpp#L4878C21-L4878C21
Hi, I'm using the error injection function of dcgm, and from the code, I don't find that the error is actually injected into the GPU hardware. I'd like to ask, is there any way to inject real errors into GPU hardware, such as ECC Errors?

**Comment by glowkey** [comment]
There is no way to inject the error into the GPU hardware. The injection API only injects the error into DCGM's internal cache.

**Comment by yaoyinnan** [comment]
@glowkey I need your help. Can the xid fault injected by dcgmi be monitored by `nvml.WaitForEvent`? For example, when using `dcgmi test --inject --gpuid 0 -f 230 -v 79` to inject a fault, it seems that only dcgmi's own `dcgmi policy --reg` can monitor it.
If I want to simulate injecting a fault that nvml can monitor, how can I implement it?

**Comment by nikkon-dev** [comment]
@yaoyinnan,

I'd say this is mostly impossible to do in a general case. NVML works in a process and directly communicates with the driver. Another process cannot "inject" anything into this communication. This could be quasi-solved if you use a proxy between the NVML and your application in a way that you call a proxy function instead of the NVML one. This way, you are in control of what that function returns, and you can check how your application reacts to this.

We did a similar solution for our testing needs, and you can check it [here](https://github.com/NVIDIA/DCGM/tree/master/nvml-injection)

**Comment by maxweiss** [comment]
> Is there anyway we can inject error and let DCGM diagnostic test to fail? How can we mock a failed DCGM diagnostic test?

For example:
```
dcgmi test --inject --gpuid 0 -f 202 -v 99999
```

See https://docs.nvidia.com/datacenter/dcgm/latest/user-guide/dcgm-error-injection.html.
