### ISSUE TITLE
Docker build fails at "Retrieving 'isl-0.24'"

### ISSUE THREAD

**Issue by ctl-dev** [NVIDIA/DCGM#15]
The source code was downloaded from Github and build under Ubuntu 20.04 on Intel Platform. Apparently the code failed to build at the line "Retriebing 'isl-0.24'". After doing a search, the line is found in the file 'x86_64.config' under "dcgmbuild" directory. Apparently, when the build script tried to fetch the "isl-0.24" package from "isl.gforge.inria.fr", it failed. Changing the line "CT_ISL_MIRROTS" to point to "http://libisl.sourceforge.io" seems to  solve the build issue.

**Comment by nikkon-dev** [comment]
Hello, 

This is a known issue with the isl dependency for GCC. We are preparing a newer version of DCGM for publication on GitHub and the issue is already fixed there.

As an alternative, you could update the crosstool-ng commit that is mentioned in the Dockerfile to point to a crosstool-ng latest commit where this issue is also already fixed.
